# Generated by Django 3.2.4 on 2021-07-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETTEKAA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
