# Generated by Django 3.2.4 on 2021-07-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETTEKAA', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
